apiVersion: apps/v1
kind: Deployment
metadata:
 name: bmi
 labels:
  app: bmi
spec:
 replicas: 1
 selector:
  matchLabels:
   app: bmi
 template:
  metadata: 
   labels:
    app: bmi
  spec:
   containers:
   - name: bmi
     image: ishu1108/docker-jenkins:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bmi
spec:
  type: LoadBalancer
  selector:
    app: bmi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
